name: metrics
channels:
  - conda-forge
dependencies:
  - pandas
  - ipympl
  - jupyter
  - ipython
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - voila
  - jupyter_contrib_nbextensions
